items = [
    {"type": "素材", "name": "木材", "amount": 3},
    {"type": "素材", "name": "火打石", "amount": 0},
    {"type": "素材", "name": "生肉", "amount": 1},
    {"type": "素材", "name": "石ころ", "amount": 3},
    {"type": "アイテム", "name": "焚き火", "amount": 0},
    {"type": "消耗品", "name": "焼き肉", "amount": 1},
    {"type": "消耗品", "name": "いかだ", "amount": 1},
    {"type": "素材", "name": "海水", "amount": 3},
    {"type": "消耗品", "name": "水", "amount": 0},
    {"type": "素材", "name": "繊維", "amount": 0},
    {"type": "アイテム", "name": "浄水器", "amount": 0},
    {"type": "アイテム", "name": "斧", "amount": 1},
    {"type": "アイテム", "name": "弓", "amount": 0},
    {"type": "アイテム", "name": "つるはし", "amount": 0},
    {"type": "素材", "name": "プラスチック ", "amount": 0},
    {"type": "素材", "name": "厚板", "amount": 0},
    {"type": "アイテム", "name": "木工機", "amount": 0},
    {"type": "素材", "name": "レンガ", "amount": 0},
    {"type": "アイテム", "name": "石工機", "amount": 0},
]
